const ReportDetails = () => {
  return (
    <div className="bg-white p-6 rounded-xl shadow">

      <h1 className="text-3xl font-bold mb-5">
        Report Details
      </h1>

      <div className="space-y-4">

        <p>
          Report Name: Monthly Sales Report
        </p>

        <p>
          Generated By: Admin
        </p>

        <p>
          Generated Date: 2026-05-28
        </p>

        <p>
          Status: Completed
        </p>

      </div>

    </div>
  );
};

export default ReportDetails;